### ISSUE TITLE
Caching problems

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#1]
From Henry:

I have update the sponsors_logos.mhtml file (see screen shot) and restarted the server but the changes have not reflected please advise me on what I am doing wrong

and:

When I goto http://babvs60.rothamsted.ac.uk:5000/test i seen the images but when I
goto http://babvs60.rothamsted.ac.uk:5000 don't see the images.

**Comment by kimrutherford** [comment]
My suggestions:

 - try shift-reload in the browser
 - try stopping the server then reload the page in the browser to confirm that nothing is being cached and that you're looking at the right URL
 - check the source with view-source in the browser
 - try the dev-tools in the browser to see what is cached

**Comment by henryosim** [comment]
@kimrutherford Ive tried points 1-3 and still not working. 

> check the source with view-source in the browser
the view-source only shows the old cached version not my updated code.

**Comment by kimrutherford** [comment]
Now I have a copy of the changes I can reproduce the problem.  I'm not sure what the problem is.  I'm working on it and I'll let you know when I've got a fix.

**Comment by kimrutherford** [comment]
Hi.  I think I've fixed the problem.  It wasn't obvious, but there were three copies of the `sponsor_logos.mhtml` file and you edited one copy.

Sorry about that.  There shouldn't haven't been three copies so I've removed two and made symbolic links so that everything works OK.

If you pull the latest changes from the main Canto repository it should fix your problem.

**Comment by henryosim** [comment]
it works thanks
