### ISSUE TITLE
Error: No genes found for these identifiers: Q00909

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#10]
From @henryosim:

Please how do I get rid of this message?

![unnamed](https://user-images.githubusercontent.com/90474/34154991-82eb06d2-e51c-11e7-8ccf-089ca5a7ed65.png)

**Comment by henryosim** [comment]
i tried this `./script/canto_load.pl --ontology  http://purl.obolibrary.org/obo/go/go-basic.obo`  but didnot work

**Comment by ValWood** [comment]
What is the error message?
Kim will be in bed now but he will be able to take a look tomorrow (he is working half day tomorrow).

Is this the correct field in the  UniProt XML though? 
Try a UniProt Identifier e.g.  ALP4_SCHPO or a gene name e.g.  ORF name SPBC365.15
and see if you get anything?

This would relate to one of your tasks, to make sure  that you are retrieving the required fields from the UniProt database using the XML.
https://github.com/PHI-base/canto/issues/3


I think this closed ticket tells you that the field that is being retrieved at present is not the one you need? I might be mistaken, but  I think from reading this ticket
https://github.com/PHI-base/canto/issues/3
that Kim got   the look-up itself working so you could configure correctly.

I think you discussed this with @CuzickA  so hopefully she can explain.

**Comment by kimrutherford** [comment]
> Please how do I get rid of this message?

Please add your `canto_deploy.yaml` to Git and push it to GitHub so we can check that the UniProt adaptor configuration is correct.

Are you using the same `canto_deploy.yaml` on the server and on your development machine?  The UniProt lookup was working in your development version.

**Comment by kimrutherford** [comment]
> i tried this ./script/canto_load.pl --ontology http://purl.obolibrary.org/obo/go/go-basic.obo but didnot work

Loading the ontology terms won't fix the UniProt lookup - they're independent.

**Comment by henryosim** [comment]
> Please add your canto_deploy.yaml to Git and push it to GitHub so we can check that the UniProt adaptor configuration is correct.

The `canto_deploy.yaml` file has been uploaded [here](https://github.com/PHI-base/canto/blob/master/canto_deploy.yaml)
