### ISSUE TITLE
Duplication of UniProt Gene Name in Synonyms Column

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto#11]
It is great that the UniProt Entry name has been removed and replaced with the Gene name. However, it appears that the Gene name is present in both the 'Name' column and 'Synonyms' column. Does this matter?
screenshot from a random gene to demonstrate
![uniprot gene name duplication](https://user-images.githubusercontent.com/11753634/34567428-276c1c3e-f15a-11e7-9e45-37b7013abfb5.PNG)

**Comment by kimrutherford** [comment]
> the Gene name is present in both the 'Name' column and 'Synonyms' column

That should be easy to fix.  It's not something we've had to worry about at PomBase because the curators are careful to make sure that doesn't happen.

**Comment by ValWood** [comment]
This isn't  a uniprot curation issue, it's a parsing issue.
@henryosim  needs to make sure that the "name field" is not duplicated in the synonym field.

![names](https://user-images.githubusercontent.com/7359272/34807418-9f872ba2-f680-11e7-96f0-d96aaa35319d.jpg)

**Comment by ValWood** [comment]
i.e 
"name" is "name"
"ordered locus" and "orf name" are "synonyms"

**Comment by kimrutherford** [comment]
> This isn't a uniprot curation issue, it's a parsing issue.

I should have looked at the XML - you're right.

**Comment by henryosim** [comment]
@kimrutherford would you like me to modify the code for locally or do you want to make changes to the master project?

**Comment by kimrutherford** [comment]
> would you like me to modify the code for locally or do you want to make changes to the master project?

Please go ahead and make the changes.  I'll pull them into the PomBase version later.

**Comment by henryosim** [comment]
I added a shift function to the @synonyms array to remove the gene name from the array see code changes [here ](https://github.com/PHI-base/canto/blob/d96a3ec6bff16c85c698d5c01883ffa054825331/lib/Canto/UniProt/UniProtUtil.pm#L81)

see screen shot of preview below:
![genename-and-synonym-duplication-solution](https://user-images.githubusercontent.com/6264608/35043844-0809e534-fb86-11e7-9009-d6df54590c81.PNG)

**Comment by ValWood** [comment]
It would make more sense to fix this at source upstream in the XML parsing?

**Comment by ValWood** [comment]
i.e this sounds like a hack.

**Comment by kimrutherford** [comment]
Hi Henry.

Could you tidy up the code a bit?

This code does nothing now because there is nothing between the curly brackets:

```perl
    if (defined $entry->{gene}->[0]->{name}) {
    }
```

Could you remove this comment too, as it's just a copy of the next line:

```perl
#     push @synonyms, map { _content($_) } @{$entry->{gene}->[0]->{name}};
```

**Comment by kimrutherford** [comment]
I think it would be better to use the type attribute in the XML to decide which gene name is the primary.  ie. use the name element with `type="primary"` as the gene name and then use the other name elements as synonyms.

The current code assumes that the first gene element in the XML is always the primary gene name.  For Q00909 just using the first name as the gene name works:

```xml
<gene>
  <name type="primary">TRI5</name>
  <name type="ORF">FGRRES_03537</name>
  <name type="ORF">FGSG_03537</name>
</gene>
```

but there is no guarantee that UniProt will keep that order in future.  There are already occasional UniProt entries where there is no primary gene name.

eg. A0A1Q3E1B1:

```xml
<gene>
  <name type="ORF" evidence="7">LENED_002604</name>
</gene>
```

in those cases we probably shouldn't set the gene name.

**Comment by ValWood** [comment]
> in those cases we probably shouldn't set the gene name.

We still need a "name" though.
We use the systematic ID as the name for PomBase if we do not yet have a primary name assigned.

However, this case has 2 "ORF" names. I guess it doesn't really matter which one is used.
Presumably in a paper a primary name will be assigned so ideally UniProt would  be informed and the primary name would be added.
This should all work, the orf name will only be a "place holder" .

This is something I hadn't really considered because at PomBase  we have control of  all the 
names.

Lets keep it as it is for now, it isn't a major issue and it can be refined later. One possibility would  be to have a "name override file" for known names that are not in UniProt.

For example  the file the  japonicus people are creating to populate their names, we could say if this file is present for a particular species/name  it took precedent over the Uniprot name.

Something to think about

**Comment by kimrutherford** [comment]
> We still need a "name" though.

I think it's OK in Canto for gene to not have a name.  Not every pombe gene has a name but they all have a systematic ID so it works in the interface.

**Comment by henryosim** [comment]
thank you @ValWood and @kimrutherford i will implement accordingly

**Comment by kimrutherford** [comment]
Hi @henryosim 

Have you made any progress on this?  If you are stuck please ask questions.
