### ISSUE TITLE
Decide on a simple format for taxon/strain file

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#15]
@CuzickA @martin2urban Alayne/Martin/Kim: decide on a simple format for taxon/strain file

(Moved from https://github.com/pombase/canto/issues/1347)

**Comment by kimrutherford** [comment]
It would help if the organisms were specified using the NCBI taxon ID because that's what Canto uses internally.

**Comment by CuzickA** [comment]
Do you have a list of all Pathogen Species and Species level NCBI taxon IDs/ Host Species and Species level NCBI taxon IDs? @martin2urban 

Note: We discussed yesterday that we would only use NCBI taxon IDs at the species level and NOT for the strains as NCBI are no longer assigning IDs to new strains. Strains will be a controlled name.

**Comment by martin2urban** [comment]
List on  Pathogen Species and Species level NCBI taxon IDs available at:
[http://www.phi-base.org/images/pathogen_species_list.csv](url)
Host Species and Species level NCBI taxon IDs available at: 
[http://www.phi-base.org/images/host_species_list.csv](url)

(info in first two columns)

**Comment by kimrutherford** [comment]
Hi.

What was the decision on the format?

Is this it?:

column 1: taxon ID
column 2: genus + species (for documentation)
column 3: strain name

Could you make an example we can use for testing and add it to the PHI-Canto repository?  Thanks.

Here is where the other test data file are located:
  https://github.com/PHI-base/canto/tree/master/t/data/

**Comment by CuzickA** [comment]
This seems logical to me. @henryosim showed me an example for Fusarium graminearum last week, perhaps he could add this data to the repository. Thanks

**Comment by kimrutherford** [comment]
On Tuesday 23 January 2018 at 09:06:38, Martin Urban wrote:                                    
> Hi Kim and Henry, 
> Regarding the sample file:
>   1.  I understand that the “t” directory for
>       PHI-base/canto/tree/master/t/data/ is only for test data?

Yes, only test data goes in that directory.  When we add the code to
read the taxon+strain file into Canto, we'll add a test that reads the
sample file to confirm that the code works.

>   2.  What is the preferred format for lists on Canto Github?
>     I see beneath for the ‘pombe_genes.txt’ (beneath screenshot),   a
>     tab separated list and speech marks for “conserved fungal protein”?
>     How is this generated? From Excel?
                                                                                                                                                                                              
Most of the test data files for Canto have been generated manually with a
text editor.

There is no need to quote values in the file - the values won't contain tabs
so there will be no confusion while parsing.

> Or could I upload any format?

A tab separated file in text would be easiest to process in Canto.

Thanks.

**Comment by kimrutherford** [comment]
> @henryosim showed me an example for Fusarium graminearum last week, perhaps he could add this data to the repository.

That would be great.

**Comment by ValWood** [comment]
I'm not sure why our test file has
“conserved fungal protein”
all of our "real" fils are tab delimited, no quotes anywhere.
Which file is this?

**Comment by ValWood** [comment]
Oh, maybe this file has been exported from a text editor and has control characters. Who made it?

**Comment by kimrutherford** [comment]
> Oh, maybe this file has been exported from a text editor and has control characters. Who made it?

I made it in August 2010.  :-)

It's a file for testing loading a list of genes into Canto.  The functionality is still there even though we don't use it.  The Perl TSV loader can cope with the quotes.
