### ISSUE TITLE
Add a new internal Canto Adaptor interface for strain lookup

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#19]
However we decide to store the organism to strain mapping we will need to add an internal adaptor/interface to access the mapping.

**Comment by kimrutherford** [comment]
I've added a skeleton version of the adaptor with no implementation:
  https://github.com/pombase/canto/blob/master/lib/Canto/Track/StrainLookup.pm

**Comment by kimrutherford** [comment]
To allow testing, the skeleton StrainLookup now returns some dummy data: [{"name":"strain one"},{"name":"strain two"}]

For now it returns the same dummy data no matter what taxon ID gets passed to the lookup() method.

**Comment by henryosim** [comment]
> I've added a skeleton version of the adaptor with no implementation:
https://github.com/pombase/canto/blob/master/lib/Canto/Track/StrainLookup.pm

@kim whats the best way to pull this without any issues? should I
`git checkout aq
git rebase master`

or just 
`git merge master` ?

**Comment by kimrutherford** [comment]
You'll need to add the PomBase Canto repository as a remote if you haven't already:

    git remote add pombase-canto https://github.com/pombase/canto.git

You should then be able to pull and merge the changes with:

    git pull pombase-canto master

You'll need to do another schema version upgrade on your test database after merging:

    /canto/script/canto_docker ./etc/upgrade_db.pl 16
