### ISSUE TITLE
Add the PHI-Canto configuration file to the Git repository

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#2]
The canto_deploy.yaml file should be added to Git and pushed to GitHub.

**Comment by kimrutherford** [comment]
Hi @henryosim, in commit e2e11ea7eea00a1dd81a1d26545910b47e543a31 you checked in changes to `canto.yaml`.  That file contains the configuration defaults.

Your PHI-base specific configuration should be added to `canto_deploy.yaml` as described here:
  https://curation.pombase.org/docs/canto_admin/configuration_file

For example you changed:

    long_name: Community curation application

to:

    long_name: Curation application for PHI-base, the Pathogen-Host Interactions database

Instead, you can just add your `long_name` to `canto_deploy.yaml`.

Could you please revert the changes to `canto.yaml` and put your configuration in `canto_deploy.yaml`.

Thanks.

**Comment by henryosim** [comment]
#2  [canto_deploy.yaml](https://github.com/PHI-base/canto/blob/master/canto_deploy.yaml) has been added to github repo
