### ISSUE TITLE
Add the list of host organisms to the configuration file

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#25]
It would be useful to add a configuration item that contains the taxon IDs of the known host organisms.  This will allow us to guess which genes are host genes in a lot of cases.

**Comment by CuzickA** [comment]
see #15 need list of pathogen and host species with NCBI taxon IDs @martin2urban

**Comment by martin2urban** [comment]
List on Pathogen Species and Species level NCBI taxon IDs available at:
http://www.phi-base.org/images/pathogen_species_list.csv
Host Species and Species level NCBI taxon IDs available at:
http://www.phi-base.org/images/host_species_list.csv

(info in first two columns)

**Comment by ValWood** [comment]
out of date
