### ISSUE TITLE
Decide how to display host vs pathogen genes on the front page

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#29]
Currently there is just a single list of genes that is displayed in two columns.  For PHI-Canto, a split into a host column and a pathogen column might make sense.  Would that work?

![front_page_gene_list-2018-01-16](https://user-images.githubusercontent.com/90474/34979749-267fc260-fb07-11e7-9112-b8d605d4f955.png)

**Comment by CuzickA** [comment]
sounds good and also perhaps colour coding may help when creating the pathogen/host 'metagenotype'.

I think we still haven't decided WHEN to add the host gene/ Taxon ID information? 
Either 
1) all upfront but may be difficult to capture the host taxon id when no specific host gene is mentioned
2) or as mocked up in the latest slide sets. Capture pathogen gene up front and then add the host information later on based on the 'curation type' that is selected.
