### ISSUE TITLE
Fix the Canto UniProt XML loader to retreive the gene name

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#3]
Here is a sample XML file:
  https://github.com/PHI-base/canto/blob/master/t/data/uniprot_lookup.xml

The line to change is:
  https://github.com/PHI-base/canto/blob/dc35fda893eaa2aa12df8bf85fa7f34bf78d4280/lib/Canto/UniProt/UniProtUtil.pm#L70

Currently the code gets the "name" from the UniProt entry, but unfortunately that's not the gene name, it's the entry name.  We're getting that name from this line:
  https://github.com/PHI-base/canto/blob/master/t/data/uniprot_lookup.xml#L6

But we actually need to get the gene name from this line:
  https://github.com/PHI-base/canto/blob/master/t/data/uniprot_lookup.xml#L16

You can run the test for this code with:

    dcanto perl -Ilib t/70_uniprot_util.t 

It's probably a good idea to check that the test works for you before changing the code.

**Comment by henryosim** [comment]
running `dcanto perl -Ilib t/70_uniprot_util.t ` in 'canto-space' directory returns 

> -bash: dcanto: command not found

**Comment by kimrutherford** [comment]
> dcanto: command not found

Sorry, I cut-and-pasted the wrong line.  Try:

    ./canto/script/canto_docker perl -Ilib t/70_uniprot_util.t

**Comment by henryosim** [comment]
updated

**Comment by ValWood** [comment]
@henryosim Please add details to this ticket of what you actually did.

**Comment by henryosim** [comment]
changed  https://github.com/PHI-base/canto/blob/dc35fda893eaa2aa12df8bf85fa7f34bf78d4280/lib/Canto/UniProt/UniProtUtil.pm#L70 to ` $name = _content($entry->{gene}->[0]->{name}->[0]);`

I also added `implementation_classes:
  gene_adaptor: Canto::UniProt::GeneLookup
  ontology_adaptor: Canto::Track::OntologyLookup
  status_adaptor: Canto::Track::StatusStorage
  person_adaptor: Canto::Track::PersonLookup
  pubs_adaptor: Canto::Track::PubsLookup` to the [canto_deploy.yaml](https://github.com/PHI-base/canto/blob/master/canto_deploy.yaml)
