### ISSUE TITLE
Try to set up an admin account in the test instance of PHI-Canto

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#4]
The command to add an admin user is:

    dcanto script/canto_add.pl --person "Alayne Cuzick" EMAIL_ADDRESS PASSWORD ORCID admin

Replace "EMAIL_ADDRESS", "PASSWORD" and "ORCID" with Alayne's details.  I suggest using a dummy password for testing.

Test this by going to "Admin pages" in the admin menu (the gear icon beside the help at top right).  Alayne should be able to log in with email address and password.

**Comment by kimrutherford** [comment]
> dcanto script/canto_add.pl --person "Alayne Cuzick" EMAIL_ADDRESS PASSWORD ORCID admin

Sorry, that was a typo too.  It should be:

    ./canto/script/canto_docker script/canto_add.pl --person "Alayne Cuzick" EMAIL_ADDRESS PASSWORD ORCID admin

**Comment by henryosim** [comment]
updates applied

**Comment by henryosim** [comment]
i executed command `./canto/script/canto_docker script/canto_add.pl --person "Alayne Cuzick" alayne.cuzick@rothamsted.ac.uk alaynePass 0000-0001-8941-3984 admin` and restarted the server.
when I try to login, i get 

> Login error
Incorrect email address or password, please try again

**Comment by kimrutherford** [comment]
Did you see any messages or errors when you ran `./canto/script/canto_docker script/canto_add.pl ...`?

Could you have a look and see if there are any entries in the `person` table of the Canto database?  The Canto SQLite database file is `canto-space/data/track.sqlite3`

Thanks.

**Comment by henryosim** [comment]
There are no error messages, but this is what gets output to the command line automatically  ![capture](https://user-images.githubusercontent.com/6264608/34238624-8b193cd2-e5fa-11e7-9c9e-ea43a6f5e3b8.PNG)

**Comment by henryosim** [comment]
on the command line I have deleted the initial person entry with `./canto/script/canto_docker script/canto_delete.pl --person "alayne.cuzick@rothamsted.ac.uk"
`  and added the user again `./canto/script/canto_docker script/canto_add.pl --person "Alayne Cuzick" alayne.cuzick@rothamsted.ac.uk password 0000-0001-8941-3984  admin
` and it works, user is now able to login with email and password
