### ISSUE TITLE
Create 2 column file species/strain

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#5]
From Dec. 11 meeting minutes:

KH-K can make list for fusarium.
@CuzickA will tidy up the strain list afterwards.

This will be  a config file for PHI canto.

Couple of options. 1. Config file 2. Load into Canto database. Could work a bit like “conditions”

**Comment by ValWood** [comment]
@CuzickA

**Comment by ValWood** [comment]
duplicate
