### ISSUE TITLE
triage options for PHI canto

### ISSUE THREAD

**Issue by ValWood** [PHI-base/canto#6]
@CuzickA will supply a set of triage options
(are triage options in a config file ?)
(Alayne remember that the triage options are mutually exclusive)

@CuzickA will supply a list of test publications. The PHIBAse triage is currently quite complicated. We should discuss this on a future call.
For starters can we import from a list?

**Comment by ValWood** [comment]
> are triage options in a config file ?

Yes, sort of.  The options are in the config file, but they are written into the database when a new Canto instance is created.  Henry's test Canto will have the PomBase options.

The triage options can be added to the Canto database after the instance is created but it's easier to get them sorted out up front as much as possible.
from @kimrutherford 
> For starters can we import from a list?

Yep, there a tool that comes with Canto that can load publications given a list of PubMed IDs.

**Comment by ValWood** [comment]
Alayne also mentioned that PHI-Base molecular interactions collaborators curate in "batches"
It would be nice to be able to "label" paper as being in a specific "batch"
(this might be for later, but we should discuss possibilities)

**Comment by kimrutherford** [comment]
> Yep, there a tool that comes with Canto that can load publications given a list of PubMed IDs.

@henryosim if you'd like to try adding some publications from the command line, try:

    ./canto/script/canto_docker script/canto_add.pl --pubmed-by-id 703759 318606 141274

You can run this once for each publication or you can put multiple IDs on one line which makes things faster.

**Comment by kimrutherford** [comment]
< The triage options can be added to the Canto database after the instance is created but it's easier to get them sorted out up front as much as possible.

The initial triage options are here:
  https://github.com/PHI-base/canto/blob/e2e11ea7eea00a1dd81a1d26545910b47e543a31/canto.yaml#L248

As an example, to add a new triage option called "New triage option" to an existing Canto:

```sh
./canto/script/canto_docker script/canto_add.pl \
    --cvterm 'Canto publication triage status' 'New triage option' \
    Canto:new_triage_option 
```

(Split over multiple lines for easy reading)

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/1458
and
https://github.com/pombase/canto/issues/1459
